config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :album_users
    resources :answers
    resources :rank_choices
    resources :events
    resources :event_comments
    resources :graduation_albums
    resources :message_for_each_menbers
    resources :message_for_everyones
    resources :photo_collections
    resources :photo_paths
    resources :ranks
    resources :registered_collections
    resources :relationships
    resources :suprise_messages

    root to: 'users#index'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'

  devise_scope :user do
    get 'edit', to: 'users/registrations#edit'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
  end
  get 'users/show' => 'users#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome_pages#top'
  resources :sample_album_pages, only: %i[index] do
    collection do
      get :detail
    end
  end
  get 'static_pages/privacy' => 'static_pages#privacy'
  get 'static_pages/terms_service' => 'static_pages#terms_service'
  post '/welcome_pages/guest_sign_in', to: 'welcome_pages#guest_sign_in'
  resources :graduation_albums do
    member do
      delete :destroy_each_photo
    end
    resources :menbers, only: %i[show] do
      resources :register_faces, only: %i[create]
    end
    resources :ranks, only: %i[create update edit destroy new show] do
      resources :rank_choices, only: %i[create update edit destroy new show]
    end
    resources :events, only: %i[create update edit destroy new show] do
      resources :event_comments, only: %i[create edit destroy update]
    end
    resources :message_for_everyones, only: %i[create edit destroy update]
    resources :message_for_each_menbers, only: %i[create edit destroy update]
    resources :suprise_messages, only: %i[create edit destroy update new show]
    resources :auto_make_events, only: %i[create]
    resources :auto_make_ranks, only: %i[create]
  end
  resources :answers, only: %i[create]
  resources :relationships, only: %i[create destroy]
end

app/controllers/menbers_controller.rb
# frozen_string_literal: true

class MenbersController < ApplicationController
  before_action :authenticate_user!
  include AwsRekognition

  def show
    @graduation_album = current_user.belong_albums.find(params[:graduation_album_id])
    @menber = User.find(params[:id])
    if @menber.face_id && @graduation_album.analysis_status == 'done'
      resp = collect_menber_faces(@menber)
      if resp
        mathed_faces = []
        resp[:face_matches].size.times { |face| mathed_faces.push(resp[:face_matches][face][:face][:image_id]) }
        @mathed_face_images = []
        mathed_faces.each do |image|
          photo_path = PhotoPath.where(graduation_album_id: @graduation_album.id).where(image_id: image).first
          @mathed_face_images.push(ActiveStorage::Attachment.where(record_id: @graduation_album.id).where(blob_id: photo_path.path.to_i).first) if photo_path
        end
      end
    end
    @message_for_each_menbers = @graduation_album.message_for_each_menbers.where(to_user: @menber.id).includes(:user).order(created_at: :desc)
    @message_for_each_menber = MessageForEachMenber.new
    @ranks = @menber.ranks.where(graduation_album_id: @graduation_album.id).includes([:graduation_album])
    @suprise_messages = @menber.suprise_messages.where(graduation_album_id: @graduation_album.id).includes([:graduation_album])
    @events = @menber.events.where(graduation_album_id: @graduation_album.id).with_attached_event_photos.includes([:graduation_album])
  end
end

app/views/menbers/show.html.erb
<% breadcrumb :menber_show, @graduation_album, @menber %>
<div class="bg-white py-6 sm:py-8 lg:py-12">
  <div class="max-w-screen-xl px-4 md:px-8 mx-auto">
    <div class="mb-10 md:mb-16">
      <div class="flex flex-col items-center rounded-lg p-4 lg:p-8">
          <div class="w-24 md:w-32 h-24 md:h-32 bg-gray-200 rounded-full overflow-hidden shadow-lg mb-2 md:mb-4">
            <%= image_tag @menber.avatar.to_s %>
          </div>
          <div>
            <div class="text-blue-500 md:text-lg font-bold text-center">
              <%= @menber.name %>
            </div>
          <% if @graduation_album.analysis_status == 'done'%>
          <div class='flex justify-center'>
            <%= link_to graduation_album_menber_register_faces_path(@graduation_album, @menber), method: :post do %>
              <button class="bg-blue-500 hover:bg-blue-300 text-white rounded px-4 py-2"><%=@menber.name%>さんの写真を取得</button>
            <% end %>
          </div>
          <% elsif @graduation_album.analysis_status == 'doing' %>
            <p class='pt-6 text-center text-blue-500'> アルバムに投稿された画像を分析中です</p>
            <p class='pb-6 text-center text-blue-500'> 分析が終わるとアルバムに投稿された画像の中から<%=@menber.name%>さんが写っている写真をこのページに表示できます</p>
          <% else %>
            <p class='pt-6 text-center text-blue-500'> アルバムに写真を投稿してみよう！</p>
            <p class='pb-6 text-center text-blue-500'> 投稿するとアルバムの画像の中から<%=@menber.name%>さんが写っている写真をこのページに表示できます</p>
          <% end %>
          </div>
          <div class="grid grid-cols-2 sm:grid-cols-3 gap-4 md:gap-5 xl:gap-2 pt-6">
            <% if @mathed_face_images && @mathed_face_images.count != 0 %>
              <% @mathed_face_images.each do |image| %>
                <div class="photo transform -rotate-12">
                  <%= image_tag image.variant(gravity: :center, resize:"640x640^", crop:"640x640+0+0").processed %>
                </div>
              <% end %> 
            <% end %>
          </div>
      <h2 class="text-red-400 text-2xl lg:text-3xl font-bold text-center pt-4 mb-4 md:mb-6 pt-10"><i class="fa-regular fa-comment"></i>メンバーからのメッセージ</h2>
    </div>
    <%= render 'message_for_each_menbers/message_for_each_menbers', { message_for_each_menbers: @message_for_each_menbers } %>
    <%= render 'message_for_each_menbers/form', { graduation_album: @graduation_album, message_for_each_menber: @message_for_each_menber, menber: @menber } %>
    
        <% unless @menber.events == [] %>
      <div class="mb-10 md:mb-16">
        <h2 class="text-indigo-700 text-2xl lg:text-3xl font-bold text-center mb-6 mt-12 md:mb-6"><%= "#{@menber.name}"%>さんが作成したイベント</h2>
      </div>
      <%= render 'events/events', { graduation_album: @graduation_album, events: @events } %>
    <% else %>
      <div class="my-5 md:my-8">
        <h3 class="text-indigo-700 text-2xl font-bold text-center mb-6 mt-6 md:mb-6"><%= "#{@menber.name}"%>さんが作成したランキングはまだありません</h3>
        <%= render 'graduation_albums/event_explanation' %>
      </div>
    <% end %>
    <div class='text-center py-3'>
      <%= link_to new_graduation_album_event_path(@graduation_album) do %>
        <button class="btn btn-outline btn-primary">イベントを作成</button>
      <% end %>
    </div>

    <% unless @menber.ranks == [] %>
      <div class="my-5 md:my-8">
        <h2 class="text-pink-500 text-2xl lg:text-3xl font-bold text-center mb-6 mt-6 md:mb-3"><%= "#{@menber.name}"%>さんが作成したランキング</h2>
      </div>
      <%= render 'ranks/ranks', { graduation_album: @graduation_album, ranks: @ranks } %>
    <% else %>
      <div class="my-5 md:my-8">
        <h3 class="text-pink-500 text-2xl font-bold text-center mb-6 mt-6 md:mb-6"><%= "#{@menber.name}"%>さんが作成したランキングはまだありません</h3>
        <%= render 'graduation_albums/rank_explanation' %>
      </div>
    <% end %>
    <div class='text-center py-3'>
      <%= link_to new_graduation_album_rank_path(@graduation_album) do %>
        <button class="btn btn-outline btn-secondary">ランキングを作成</button>
      <% end %>
    </div>

    <% unless @menber.suprise_messages == [] %>
      <div class="mb-10 md:mb-16">
        <h2 class="text-green-600 text-2xl lg:text-3xl font-bold text-center mb-6 mt-12 md:mb-6"><%= "#{@menber.name}"%>さんが作成したサプライズメッセージ</h2>
      </div>
      <%= render 'suprise_messages/suprise_messages', { graduation_album: @graduation_album, suprise_messages: @suprise_messages } %>
    <% else %>
      <div class="my-5 md:my-8">
        <h3 class="text-green-600 text-2xl font-bold text-center mb-6 mt-6 md:mb-6"><%= "#{@menber.name}"%>さんが作成したランキングはまだありません</h3>
        <%= render 'graduation_albums/suprise_explanation' %>
      </div>
    <% end %>
    <div class='text-center py-3'>
      <%= link_to new_graduation_album_suprise_message_path(@graduation_album) do %>
        <button class="btn btn-outline btn-accent">サプライズメッセージを作成</button>
      <% end %>
    </div>
  </div>
</div>