config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :album_users
    resources :answers
    resources :rank_choices
    resources :events
    resources :event_comments
    resources :graduation_albums
    resources :message_for_each_menbers
    resources :message_for_everyones
    resources :photo_collections
    resources :photo_paths
    resources :ranks
    resources :registered_collections
    resources :relationships
    resources :suprise_messages

    root to: 'users#index'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'

  devise_scope :user do
    get 'edit', to: 'users/registrations#edit'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
  end
  get 'users/show' => 'users#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome_pages#top'
  resources :sample_album_pages, only: %i[index] do
    collection do
      get :detail
    end
  end
  get 'static_pages/privacy' => 'static_pages#privacy'
  get 'static_pages/terms_service' => 'static_pages#terms_service'
  post '/welcome_pages/guest_sign_in', to: 'welcome_pages#guest_sign_in'
  resources :graduation_albums do
    member do
      delete :destroy_each_photo
    end
    resources :menbers, only: %i[show] do
      resources :register_faces, only: %i[create]
    end
    resources :ranks, only: %i[create update edit destroy new show] do
      resources :rank_choices, only: %i[create update edit destroy new show]
    end
    resources :events, only: %i[create update edit destroy new show] do
      resources :event_comments, only: %i[create edit destroy update]
    end
    resources :message_for_everyones, only: %i[create edit destroy update]
    resources :message_for_each_menbers, only: %i[create edit destroy update]
    resources :suprise_messages, only: %i[create edit destroy update new show]
    resources :auto_make_events, only: %i[create]
    resources :auto_make_ranks, only: %i[create]
  end
  resources :answers, only: %i[create]
  resources :relationships, only: %i[create destroy]
end

app/views/shared/_album_header.html.erb
<header>
  <div class="navbar bg-green-100">
    <div class="flex-1">
      <%= link_to 'Web卒アル', graduation_albums_path, class:"btn btn-ghost normal-case text-xl" %>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal p-0">
        <li>
          <%= link_to anchor: "event_top" do %>
            <i class="fa-solid fa-plane fa-lg"></i>
          <% end %>
        </li>
        <li>
          <%= link_to anchor: "rank_top" do %>
            <i class="fa-solid fa-ranking-star fa-lg"></i>
          <% end %>
        </li>
        <li>
          <%= link_to anchor: "suprise_top" do %>
            <i class="fa-solid fa-gift fa-lg"></i>
          <% end %>
        </li>
      </ul>
      <div class="dropdown dropdown-end" id='profile'>
        <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <%= image_tag current_user.avatar.to_s %>
          </div>
        </label>
        <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
          <li>
            <%= link_to "プロフィール", users_show_path %>
          </li>
          <% if current_user.social_unique_id %>
            <li><%= link_to 'ログアウト', '/auth/logout', method: :get %></li>
          <% else %>
            <li><%= link_to "ログアウト", logout_path %></li>
          <% end %>
          <li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_before_login_header.html.erb
<header>
  <div class="navbar bg-base-300">
    <div class="flex-1">
    <%= link_to graduation_albums_path, class:"btn btn-ghost normal-case text-xl" do %>
      <%= image_tag 'header_logo.png'%>
    <% end %>
    </div>
    <div class="flex-none px-6">
      <%= link_to 'ログイン / 新規登録', '/auth/auth0', method: :post %>
  </div>
</header>

  

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class='bg-red-300'>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'alert'%>
    <div class="alert alert-error shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <%= message%>
      </div>
    </div>
  <% else %>
    <div class="alert alert-info shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current flex-shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
        <%= message%>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-4 bg-green-100 text-base-content">
  <div class="grid grid-cols-2 gap-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-4 xl:grid-cols-4 flex justify-center">
    <div class="text-gray-700 text-center px-4 m-2">© 2022 Web卒アル</div>
    <div class="text-gray-700 text-center px-4 m-2">
      <%= link_to '利用規約', static_pages_terms_service_path %>
    </div>
    <div class="text-gray-700 text-center px-4 m-2">
      <%= link_to 'プライバシーポリシー', static_pages_privacy_path %>
    </div>
    <div class="text-gray-700 text-center px-4 m-2">
      <%= link_to 'お問い合わせ', 'https://twitter.com/yusuke_RUNTEQ31' %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="navbar bg-green-100">
    <div class="flex-1">
      <%= link_to graduation_albums_path, class:"btn btn-ghost normal-case text-xl" do %>
        <%= image_tag 'header_logo.png'%>
      <% end %>
    </div>
    <div class="flex-none px-2">
      <div class="dropdown dropdown-end" id='profile'>
        <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <%= image_tag current_user.avatar.to_s %>
          </div>
        </label>
        <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
          <li>
            <%= link_to "トップページ", root_path %>
          </li>
          <li>
            <%= link_to "プロフィール", users_show_path %>
          </li>
          <% if current_user.social_unique_id %>
            <li><%= link_to 'ログアウト', '/auth/logout', method: :get %></li>
          <% else %>
            <li><%= link_to "ログアウト", logout_path %></li>
          <% end %>
          <li>
            <% if current_user.admin == true %>
              <%= link_to "管理画面", admin_root_path %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>