config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :album_users
    resources :answers
    resources :rank_choices
    resources :events
    resources :event_comments
    resources :graduation_albums
    resources :message_for_each_menbers
    resources :message_for_everyones
    resources :photo_collections
    resources :photo_paths
    resources :ranks
    resources :registered_collections
    resources :relationships
    resources :suprise_messages

    root to: 'users#index'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'

  devise_scope :user do
    get 'edit', to: 'users/registrations#edit'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
  end
  get 'users/show' => 'users#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome_pages#top'
  resources :sample_album_pages, only: %i[index] do
    collection do
      get :detail
    end
  end
  get 'static_pages/privacy' => 'static_pages#privacy'
  get 'static_pages/terms_service' => 'static_pages#terms_service'
  post '/welcome_pages/guest_sign_in', to: 'welcome_pages#guest_sign_in'
  resources :graduation_albums do
    member do
      delete :destroy_each_photo
    end
    resources :menbers, only: %i[show] do
      resources :register_faces, only: %i[create]
    end
    resources :ranks, only: %i[create update edit destroy new show] do
      resources :rank_choices, only: %i[create update edit destroy new show]
    end
    resources :events, only: %i[create update edit destroy new show] do
      resources :event_comments, only: %i[create edit destroy update]
    end
    resources :message_for_everyones, only: %i[create edit destroy update]
    resources :message_for_each_menbers, only: %i[create edit destroy update]
    resources :suprise_messages, only: %i[create edit destroy update new show]
    resources :auto_make_events, only: %i[create]
    resources :auto_make_ranks, only: %i[create]
  end
  resources :answers, only: %i[create]
  resources :relationships, only: %i[create destroy]
end

app/models/rank.rb
# == Schema Information
#
# Table name: ranks
#
#  id                  :bigint           not null, primary key
#  rank_description    :text             not null
#  rank_title          :string           not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  graduation_album_id :bigint           not null
#  user_id             :bigint           not null
#
# Indexes
#
#  index_ranks_on_graduation_album_id  (graduation_album_id)
#  index_ranks_on_user_id              (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (graduation_album_id => graduation_albums.id)
#  fk_rails_...  (user_id => users.id)
#
class Rank < ApplicationRecord
  belongs_to :user
  belongs_to :graduation_album
  has_many :rank_choices, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :rank_title, :rank_description, presence: true
  validates :rank_title, length: { maximum: 20 }
  validates :rank_description, length: { maximum: 200 }
end

app/controllers/admin/ranks_controller.rb
module Admin
  class RanksController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rank, only: %i[update destroy edit show]
  def new
    @rank = Rank.new
    @graduation_album = GraduationAlbum.find(params[:graduation_album_id])
  end

  def create
    @rank = current_user.ranks.build(params_rank)
    @graduation_album = GraduationAlbum.find(params[:graduation_album_id])
    if @rank.save
      redirect_to graduation_album_rank_path(@rank.graduation_album, @rank), notice: 'ランキングを投稿しました'
    else
      flash.now['alert'] = 'ランキング作成に失敗しました'
      render :new
    end
  end

  def edit; end

  def show; end

  def update
    if @rank.update(params_rank)
      redirect_to graduation_album_rank_path(@rank.graduation_album, @rank), notice: 'ランキングを投稿しました'
    else
      flash.now['alert'] = 'ランキング編集に失敗しました'
      render :edit
    end
  end

  def destroy
    @rank.destroy!
    redirect_to graduation_album_path(@rank.graduation_album)
  end

  private

  def params_rank
    params.require(:rank).permit(:rank_title, :rank_description).merge(graduation_album_id: params[:graduation_album_id])
  end

  def set_rank
    @rank = GraduationAlbum.find(params[:graduation_album_id]).ranks.find(params[:id])
  end
end

app/views/ranks/_rank.html.erb
<div class="hero-content text-center self-start pt-8 ">
  <div class="card lg:card-side bg-base-100 my-6 shadow-xl border border-pink-300">
    <div class="card-body">
      <div class='p-2'>
        <div class="grid grid-cols-5 gap-4">
            <div class="col-start-1 col-span-2 sm:col-start-2 col-span-3 text-pink-500 text-center px-4 py-2 m-2 text-sm sm:text-2xl font-bold"><%= link_to "#{rank.rank_title}",graduation_album_rank_path(rank.graduation_album, rank) %></div>
            <div class="col-end-6 col-span-2 sm:col-span-1 text-pink-500 text-center px-4 py-2 m-2">
              <% if current_user.own?(rank) %>
                <%= link_to edit_graduation_album_rank_path(rank.graduation_album, rank), class: "text-pink-500 hover:text-pink-500 font-bold transition duration-100" do %>
                  <i class="fa-solid fa-pen-to-square fa-lg"></i>
                <% end %>
                <%= link_to graduation_album_rank_path(rank.graduation_album, rank), method: :delete, id: "delete_button", data: {confirm: "本当に削除しますか？"},  class: "text-pink-500 hover:text-pink-500 font-bold transition duration-100" do%>
                  <i class="fa-solid fa-trash-can fa-lg"></i>
                <% end %>
              <% else %>
                <%= link_to "詳細",graduation_album_rank_path(rank.graduation_album, rank), class:'text-pink-500 text-xs sm:text-2xl font-bold' %>
              <% end %>
            </div>
          </div>
        <div class='text-pink-500'><%= simple_format(rank.rank_description) %></div>
      </div>
      <% rank.rank_choices.order(answers_count: "DESC").with_attached_rank_choice_image.each_with_index do |choice, index| %>
        <% if choice.rank_choice_image.variant( rotate: 2 )  %>
          <div class="flex justify-center">
            <div class="group h-80 w-80 flex items-end bg-gray-100 rounded-lg overflow-hidden shadow-lg relative p-4">
            <% if index.even? %>
              <%= image_tag choice.rank_choice_image.variant( rotate: 2 ).processed, loading:"lazy", alt:"Photo by Fakurian Design", class:"w-full h-full object-cover object-center absolute inset-0 transition duration-200" %>
            <% else %>
              <%= image_tag choice.rank_choice_image.variant( rotate: -2 ).processed, loading:"lazy", alt:"Photo by Fakurian Design", class:"w-full h-full object-cover object-center absolute inset-0 transition duration-200" %>
            <% end %>
              <div class="bg-gradient-to-t from-gray-800 via-transparent to-transparent opacity-50 absolute inset-0 pointer-events-none"></div>
            </div>
          </div>
        <% end %>
        <div class="grid grid-cols-12 flex items-center my-4">
          <div class="text-sm sm:text-2xl col-span-3 text-sm font-medium text-pink-600 dark:text-pink-500 text-center">
            <i class="fa-solid fa-crown"></i> <%= link_to "#{choice.content}",edit_graduation_album_rank_rank_choice_path(rank.graduation_album, rank, choice) %>
          </div>
          <div class="self-center col-span-6 h-5 mx-4 bg-gray-200 rounded dark:bg-gray-700">
            <% unless choice.answers.count == 0 %>
              <div class="col-span-6 h-5 bg-yellow-400 rounded" style="width:<%= (choice.answers.count.quo(rank.answers.count).to_f*100).floor %>%"></div>
            <% else %>
              <div class="col-span-6 h-5 bg-yellow-400 rounded" style="width:0%"></div>
            <% end %>
          </div>
          <input type="number" value="<%= choice.answers.count %>" style="text-align:right" class='text-pink-600 text-sm sm:text-2xl inline-block col-span-1' id="textbox"><span class='text-pink-600 text-sm sm:text-2xl'>票</span>
          <span class="self-center col-span-1 text-sm font-medium text-pink-600 dark:text-pink-500 text-center">
            <%= link_to answers_path(rank_id: rank.id, id: choice.id), id:"up", class:'button', method: :post do %>
              <i class="fa-solid fa-check-to-slot fa-lg"></i>
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>


<script>
(() => {
  const upbutton = document.getElementById('up');
  const text = document.getElementById('textbox');

  upbutton.addEventListener('click', (event) => {
    text.value++;
  })
})();
</script>

app/views/ranks/_ranks.html.erb
<div class="grid grid-cols-1 sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-1 gap-6">
  <%= render @ranks %>
</div>

app/views/ranks/edit.html.erb
<div class="mt-8">
  <%= form_with model: @rank, url: [@rank.graduation_album, @rank], class:"w-10/12 mx-auto md:max-w-md", local: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>
    <div class="mb-8">
      <%= f.label :rank_title, class: "text-sm block"%>
      <%= f.text_field :rank_title, class: 'w-full py-2 border-b focus:outline-none focus:border-b-2 focus:border-indigo-500 placeholder-gray-500 placeholder-opacity-50', placeholder: "タイトル" %>
    </div>
    <div class="mb-8">
      <%= f.label :rank_description, class: "text-sm block"%>
      <%= f.text_field :rank_description, class: 'w-full py-2 border-b focus:outline-none focus:border-b-2 focus:border-indigo-500 placeholder-gray-500 placeholder-opacity-50', placeholder: "詳細" %>
    </div>
    <div class='form-control mt-6'>
      <%= f.submit '作成する', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/ranks/new.html.erb
<% breadcrumb :new_graduation_album_rank, @graduation_album %>
<div class="mt-8">
  <%= form_with model: @rank, url: graduation_album_ranks_path, class:"w-10/12 mx-auto md:max-w-md", local: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>
    <div class="mb-8">
      <%= f.label :rank_title, class: "text-sm block"%>
      <%= f.text_field :rank_title, class: 'w-full py-2 border-b focus:outline-none focus:border-b-2 focus:border-indigo-500 placeholder-gray-500 placeholder-opacity-50', placeholder: "タイトル" %>
    </div>
    <div class="mb-8">
      <%= f.label :rank_description, class: "text-sm block"%>
      <%= f.text_area :rank_description, class: 'w-full py-2 border-b focus:outline-none focus:border-b-2 focus:border-indigo-500 placeholder-gray-500 placeholder-opacity-50', placeholder: "詳細" %>
    </div>
    <div class='form-control mt-6'>
      <%= f.submit '作成する', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<div class="bg-white py-6 sm:py-8 lg:py-12">
  <div class="max-w-screen-xl px-4 md:px-8 mx-auto">
    <!-- text - start -->
    <div class="mb-5 md:mb-8">
      <h2 class="text-gray-800 text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-6">ランキングを自動で作成する</h2>
      <p class="max-w-screen-md text-gray-500 md:text-lg text-center mx-auto">アルバムに投稿された画像を感情分析して<br>幸福度の高い画像上位3つを取得してイベントを自動作成します</p>
    </div>
    <!-- text - end -->
    <div class='text-center'>
      <%= link_to graduation_album_auto_make_ranks_path(@graduation_album), method: :post do %>
        <button class="btn btn-outline btn-secondary">自動で作成する</button>
      <% end %>
    </div>
  </div>
</div>

app/views/ranks/show.html.erb
<% breadcrumb :rank_show, @rank.graduation_album, @rank %>
<div class="hero min-h-screen">
  <div class="hero-content text-center self-start pt-8">
    <div class="card lg:card-side bg-base-100 my-6 shadow-xl">
      <div class="card-body">
        <div class='p-2'>
          <div class="grid grid-cols-5 gap-4">
            <div class="col-start-2 col-span-3 text-pink-500 text-center px-4 py-2 m-2 text-2xl font-bold"><%= @rank.rank_title %></div>
            <div class="col-end-6 col-span-1 text-pink-500 text-center px-4 py-2 m-2">
              <% if current_user.own?(@rank) %>
                <%= link_to edit_graduation_album_rank_path(@rank.graduation_album, @rank), id: "edit_button", class: "text-pink-500 text-lg lg:text-xl font-bold transition duration-100 p-2" do %>
                  <i class="fa-solid fa-pen-to-square fa-lg"></i>
                <% end %>
                <%= link_to graduation_album_rank_path(@rank.graduation_album, @rank), method: :delete, id: "delete_button", data: {confirm: "本当に削除しますか？"},  class: "text-pink-500 text-lg lg:text-xl font-bold transition duration-100" do%>
                  <i class="fa-solid fa-trash-can fa-lg"></i>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class='text-pink-500'><%= simple_format(@rank.rank_description) %></div>
        </div>
        <% @rank.rank_choices.order(answers_count: "DESC").with_attached_rank_choice_image.each_with_index do |choice, index| %>
          <% if choice.rank_choice_image.variant( rotate: 2 )  %>
              <div class="group h-80 flex items-end bg-gray-100 rounded-lg overflow-hidden shadow-lg relative p-4">
              <% if index.even? %>
                <%= image_tag choice.rank_choice_image.variant( rotate: 2 ).processed, loading:"lazy", alt:"Photo by Fakurian Design", class:"w-full h-full object-cover object-center absolute inset-0 transition duration-200" %>
              <% else %>
                <%= image_tag choice.rank_choice_image.variant( rotate: -2 ).processed, loading:"lazy", alt:"Photo by Fakurian Design", class:"w-full h-full object-cover object-center absolute inset-0 transition duration-200" %>
              <% end %>
                <div class="bg-gradient-to-t from-gray-800 via-transparent to-transparent opacity-50 absolute inset-0 pointer-events-none"></div>
              </div>
          <% end %>
          <div class="grid grid-cols-12 flex items-center my-4">
            <div class="text-2xl col-span-3 text-sm font-medium text-pink-500 dark:text-pink-500 text-center">
              <i class="fa-solid fa-crown"></i><%= link_to "#{choice.content}",edit_graduation_album_rank_rank_choice_path(@rank.graduation_album, @rank, choice) %>
            </div>
            <div class="self-center col-span-6 h-5 mx-4 bg-gray-200 rounded dark:bg-gray-700">
              <% unless choice.answers.count == 0 %>
                <div class="col-span-6 h-5 bg-yellow-400 rounded" style="width:<%= (choice.answers.count.quo(@rank.answers.count).to_f*100).floor %>%"></div>
              <% else %>
                <div class="col-span-6 h-5 bg-yellow-400 rounded" style="width:0%"></div>
              <% end %>
            </div>
            <input type="number" value="<%= choice.answers.count %>" style="text-align:right" class='text-pink-500 text-2xl inline-block col-span-1' id="textbox"><span class='text-pink-600 text-2xl'>票</span>
            <span class="self-center col-span-1 text-sm font-medium text-pink-500 dark:text-pink-500 text-center">
              <%= link_to answers_path(rank_id: @rank.id, id: choice.id), id:"up", class:'button', method: :post do %>
                <i class="fa-solid fa-check-to-slot fa-2x"></i>
              <% end %>
            </span>
          </div>
        <% end %>
        <div class='pt-6'>
          <%= link_to new_graduation_album_rank_rank_choice_path(@rank.graduation_album, @rank) do %>
            <button class="btn btn-outline btn-secondary">選択肢を追加</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
(() => {
  const upbutton = document.getElementById('up');
  const text = document.getElementById('textbox');

  upbutton.addEventListener('click', (event) => {
    text.value++;
  })
})();
</script>