config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :album_users
    resources :answers
    resources :rank_choices
    resources :events
    resources :event_comments
    resources :graduation_albums
    resources :message_for_each_menbers
    resources :message_for_everyones
    resources :photo_collections
    resources :photo_paths
    resources :ranks
    resources :registered_collections
    resources :relationships
    resources :suprise_messages

    root to: 'users#index'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'

  devise_scope :user do
    get 'edit', to: 'users/registrations#edit'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
  end
  get 'users/show' => 'users#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome_pages#top'
  resources :sample_album_pages, only: %i[index] do
    collection do
      get :detail
    end
  end
  get 'static_pages/privacy' => 'static_pages#privacy'
  get 'static_pages/terms_service' => 'static_pages#terms_service'
  post '/welcome_pages/guest_sign_in', to: 'welcome_pages#guest_sign_in'
  resources :graduation_albums do
    member do
      delete :destroy_each_photo
    end
    resources :menbers, only: %i[show] do
      resources :register_faces, only: %i[create]
    end
    resources :ranks, only: %i[create update edit destroy new show] do
      resources :rank_choices, only: %i[create update edit destroy new show]
    end
    resources :events, only: %i[create update edit destroy new show] do
      resources :event_comments, only: %i[create edit destroy update]
    end
    resources :message_for_everyones, only: %i[create edit destroy update]
    resources :message_for_each_menbers, only: %i[create edit destroy update]
    resources :suprise_messages, only: %i[create edit destroy update new show]
    resources :auto_make_events, only: %i[create]
    resources :auto_make_ranks, only: %i[create]
  end
  resources :answers, only: %i[create]
  resources :relationships, only: %i[create destroy]
end

app/models/graduation_album.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: graduation_albums
#
#  id              :bigint           not null, primary key
#  album_name      :string           not null
#  analysis_status :integer          default("before"), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :bigint           not null
#
# Indexes
#
#  index_graduation_albums_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class GraduationAlbum < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  has_many :message_for_everyones, dependent: :destroy
  has_many :message_for_each_menbers, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :ranks, dependent: :destroy
  has_many :album_users, dependent: :destroy
  has_many :users, through: :album_users, source: :user
  has_many :suprise_messages, dependent: :destroy
  has_many :photo_paths, dependent: :destroy

  validates :album_name, presence: true, length: { maximum: 30 }
  enum analysis_status: { before: 0, doing: 1, done: 2 }

  validate :validate_number_of_files
  validate :validate_number_of_album

  def validate_number_of_files
    return if images.length <= 15

    errors.add(:images, 'に添付できる画像は15枚までです。')
  end

  def validate_number_of_album
    return if user.graduation_albums.length <= 2

    errors.add(:id, '作成できるアルバムは2つまでです。')
  end

  def register_images
    return if images.empty?

    image_ids = images.map(&:id)
    RegisterRekognitionJob.perform_later(image_ids)
  end

  def set_album_menbers(menber_ids, current_user)
    menber_ids ||= []
    (menber_ids << current_user).reject(&:blank?).map(&:to_i).each do |id|
      users << User.find(id)
    end
  end
end

app/controllers/admin/graduation_albums_controller.rb
module Admin
  class GraduationAlbumsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/graduation_albums_controller.rb
# frozen_string_literal: true

class GraduationAlbumsController < ApplicationController
  before_action :set_graduation_album, only: %i[update destroy]
  before_action :authenticate_user!
  def index
    @graduation_albums = current_user.belong_albums.order(created_at: :desc)
    @users = User.all
  end

  def show
    @graduation_album = current_user.belong_albums.with_attached_images.find(params[:id])
    @message_for_everyones = @graduation_album.message_for_everyones.includes(:user).order(created_at: :desc)
    @message_for_everyone = MessageForEveryone.new
    @events = @graduation_album.events.with_attached_event_photos.order(created_at: :desc)
    @ranks = @graduation_album.ranks.order(created_at: :desc)
    @suprise_messages = @graduation_album.suprise_messages.includes(:user).order(created_at: :desc)
  end

  def new
    @graduation_album = GraduationAlbum.new
    set_search
  end

  def create
    set_search
    @graduation_album = current_user.graduation_albums.build(graduation_album_params)
    @graduation_album.set_album_menbers(params[:graduation_album][:user_ids], current_user.id)
    if @graduation_album.save
      @graduation_album.register_images
      redirect_to graduation_album_path(@graduation_album), notice: '作成に成功しました'
    else
      flash.now['alert'] = '作成に失敗しました'
      render :new
    end
  end

  def edit
    @graduation_album = current_user.graduation_albums.with_attached_images.find(params[:id])
    set_search
  end

  def update
    set_search
    @graduation_album.set_album_menbers(params[:graduation_album][:user_ids], current_user.id)
    if @graduation_album.update(graduation_album_params)
      redirect_to graduation_album_path(@graduation_album), notice: '編集に成功しました'
    else
      flash.now['alert'] = '編集に失敗しました'
      render :edit
    end
  end

  def destroy
    @graduation_album.destroy!
    redirect_to graduation_albums_path, notice: 'アルバムの削除に成功しました'
  end

  def destroy_each_photo
    image = ActiveStorage::Attachment.find(params[:id])
    image.purge
    redirect_to edit_graduation_album_path(image.record_id)
  end

  private

  def graduation_album_params
    params.require(:graduation_album).permit(:album_name, images: [])
  end

  def set_graduation_album
    @graduation_album = current_user.graduation_albums.find(params[:id])
  end
end

app/views/graduation_albums/_album_explanation.html.erb
<div class="rounded-lg bg-white py-6 sm:py-8 lg:py-12 border-solid border-2 border-pink-500">
  <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <div class="md:h-80 flex flex-col sm:flex-row rounded-lg overflow-hidden">
      <!-- content - start -->
      <div class="w-full sm:w-1/2 lg:w-3/5 flex flex-col p-4 sm:p-8">
        <h2 class="text-pink-500 text-xl md:text-2xl lg:text-4xl font-bold mb-4">アルバム作成</h2>
        <p class="max-w-md text-pink-500">アルバム名とメンバーを招待するだけで簡単作成</p>
        <p class='text-pink-500'>写真も投稿してもらうと華やかなアルバムに仕上がります</p>
        <p class='text-pink-500'>アルバム内のコンテンツを増やして盛り上げよう</p>
      </div>
      <!-- content - end -->
      <!-- image - start -->
      <div class="w-full sm:w-1/2 lg:w-2/5 h-48 sm:h-auto order-first sm:order-none bg-gray-300">
        <%= image_tag 'album.png',class:"w-full h-full object-cover object-center", loading:"lazy" %>
      </div>
      <!-- image - end -->
    </div>
  </div>
</div>

app/views/graduation_albums/edit.html.erb
<% breadcrumb :graduation_album_edit, @graduation_album %>
<div class="mt-8">
  <%= form_with model: @graduation_album, class:"w-10/12 mx-auto md:max-w-2xl", local: true do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="mb-8">
      <%= f.label :album_name, class: "text-sm block"%>
      <%= f.text_field :album_name, class: 'w-full py-2 border-b focus:outline-none focus:border-b-2 focus:border-indigo-500 placeholder-gray-500 placeholder-opacity-50', placeholder: "アルバム名" %>
    </div>
    <div class="mb-8">
      <%= f.label :images, class: "text-sm block"%>
      <%= f.file_field :images, multiple: true, direct_upload: true, class: 'w-full py-2 border-b focus:outline-none focus:border-b-2 focus:border-indigo-500 placeholder-gray-500 placeholder-opacity-50' %>
    </div>
    <div class="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 gap-x-4 md:gap-x-6 gap-y-8">
      <% if @graduation_album.images %>
        <% @graduation_album.images.each do |image| %>
        <div class='flex flex-col'>
          <div class="group h-80 block bg-gray-100 rounded-lg overflow-hidden relative mb-2 lg:mb-3">
            <%= image_tag image, class:"w-full h-full object-cover object-center group-hover:scale-110 transition duration-200" %>
          </div>
          <div class='mx-auto'>
            <%= link_to '削除', destroy_each_photo_graduation_album_path(image.id), method: :delete, class: 'btn btn-danger' %>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="mb-8">
      <% unless current_user.followings.count == 0 %>
        <%= f.label :user_ids, 'メンバー', class: "text-sm block"%>
        <%= f.collection_check_boxes :user_ids, current_user.followings, :id, :name %>
      <% else %>
        <%= f.label :user_ids, 'フォローしているユーザーがいません', class: "text-sm block"%>
      <% end %>
    </div>
    <div class='form-control mt-6 pb-6'>
      <%= f.submit '作成する', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<div class="bg-white py-3 sm:py-4 lg:py-6">
  <div class="max-w-screen-xl px-4 md:px-8 mx-auto">
    <!-- text - start -->
    <div class="mb-6 md:mb-8">
      <h2 class="text-gray-800 text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-6">ユーザー検索</h2>
      <p class="max-w-screen-md text-gray-500 md:text-lg text-center mx-auto">ユーザーをフォローすることでグループに招待できます</p>
      <div class='text-center py-6'>
        <%= search_form_for @q, url: new_graduation_album_path(@graduation_album) do |f| %>
          <%= f.search_field :name_or_email_cont, placeholder:"ユーザー名 or メールアドレス", class:"input input-bordered input-accent w-full max-w-xs" %>
          <%= button_tag type: 'submit', class: "follow-btn" do %>
            <i class="fa-solid fa-magnifying-glass fa-lg pl-4"></i>
          <% end %>
        <% end %>
      </div>
    <div class="grid grid-cols-2 md:grid-cols-4 gap-x-4 lg:gap-x-8 gap-y-8 lg:gap-y-12">
      <% @users.each do |user|%>
        <div class="flex flex-col items-center">
          <div class="w-24 md:w-32 h-24 md:h-32 bg-gray-100 rounded-full overflow-hidden shadow-lg mb-2 md:mb-4">
            <%= image_tag user.avatar.to_s ,class: "w-full h-full object-cover object-center" %>
          </div>
          <div>
            <div class="text-indigo-500 md:text-lg font-bold text-center"><%= user.name %></div>
            <% unless current_user == user %>
              <% if current_user.following?(user) %>
                <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                  <%= hidden_field_tag :follow_id, user.id %>
                  <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
                <% end %>
              <% else %>
                <%= form_for(current_user.relationships.build) do |f| %>
                  <%= hidden_field_tag :follow_id, user.id %>
                  <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/graduation_albums/index.html.erb
<% breadcrumb :root %>
<div class="bg-white py-3 sm:py-4 lg:py-6">
  <div class="max-w-screen-2xl px-2 md:px-4 mx-auto">
    <!-- text - start -->
    <div class="flex justify-center items-center pb-6">
      <div class="flex flex-col border-dotted border-4 border-green-100 bg-opacity-50 px-10 py-3">
        <i class="fa-solid fa-book-open fa-5x"></i>
        <div class="py-3"><p>あなたの大切な思い出をアルバムに</p></div>
        <%= link_to new_graduation_album_path, class:"btn btn-success" do %>
          <i class="fa-solid fa-plus fa-lg pr-2 "></i>作成する
        <% end %>
      </div>
    </div>

    <div class="grid sm:grid-cols-2 gap-6">
      <% if @graduation_albums.present? %>
        <%= render @graduation_albums %>
      <% else %>
        <p>投稿はありません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/graduation_albums/new.html.erb
<% breadcrumb :graduation_album_new %>
<div class="mt-8">
  <%= form_with model: @graduation_album, class:"w-10/12 mx-auto md:max-w-2xl", local: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>
    <div class="mb-8">
      <%= f.label :album_name, class: "text-sm block"%>
      <%= f.text_field :album_name, class: 'w-full py-2 border-b focus:outline-none focus:border-b-2 focus:border-indigo-500 placeholder-gray-500 placeholder-opacity-50', placeholder: "アルバム名" %>
    </div>
    <div class="mb-8">
      <%= f.label :images, class: "text-sm block"%>
      <%= f.file_field :images, multiple: true, direct_upload: true, class: 'w-full py-2 border-b focus:outline-none focus:border-b-2 focus:border-indigo-500 placeholder-gray-500 placeholder-opacity-50' %>
    </div>
    <div class="mb-8">
      <% unless current_user.followings.count == 0 %>
        <%= f.label :user_ids, 'メンバー', class: "text-sm block"%>
        <%= f.collection_check_boxes :user_ids, current_user.followings, :id, :name %>
      <% else %>
        <%= f.label :user_ids, 'フォローしているユーザーがいません', class: "text-sm block"%>
      <% end %>
    </div>
    <div class='form-control mt-6 pb-6'>
      <%= f.submit '作成する', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<div class="bg-white py-3 sm:py-4 lg:py-6">
  <div class="max-w-screen-xl px-4 md:px-8 mx-auto">
    <!-- text - start -->
    <div class="mb-6 md:mb-8">
      <h2 class="text-gray-800 text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-6">ユーザー検索</h2>
      <p class="max-w-screen-md text-gray-500 md:text-lg text-center mx-auto">ユーザーをフォローすることでグループに招待できます</p>
      <div class='text-center py-6'>
        <%= search_form_for @q, url: new_graduation_album_path(@graduation_album) do |f| %>
          <%= f.search_field :name_or_email_cont, placeholder:"ユーザー名 or メールアドレス", class:"input input-bordered input-accent w-full max-w-xs" %>
          <%= button_tag type: 'submit', class: "follow-btn" do %>
            <i class="fa-solid fa-magnifying-glass fa-lg pl-4"></i>
          <% end %>
        <% end %>
      </div>
    <div class="grid grid-cols-2 md:grid-cols-4 gap-x-4 lg:gap-x-8 gap-y-8 lg:gap-y-12">
      <% @users.each do |user|%>
        <div class="flex flex-col items-center">
          <div class="w-24 md:w-32 h-24 md:h-32 bg-gray-100 rounded-full overflow-hidden shadow-lg mb-2 md:mb-4">
            <%= image_tag user.avatar.to_s ,class: "w-full h-full object-cover object-center" %>
          </div>
          <div>
            <div class="text-indigo-500 md:text-lg font-bold text-center"><%= user.name %></div>
            <% unless current_user == user %>
              <% if current_user.following?(user) %>
                <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                  <%= hidden_field_tag :follow_id, user.id %>
                  <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
                <% end %>
              <% else %>
                <%= form_for(current_user.relationships.build) do |f| %>
                  <%= hidden_field_tag :follow_id, user.id %>
                  <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/graduation_albums/show.html.erb
<% breadcrumb :graduation_album, @graduation_album %>
<div class="bg-white py-3 sm:py-4 lg:py-6">
  <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <!-- text - start -->
    <div class="mb-10 md:mb-16">
      <div class="bg-white py-3 sm:py-4 lg:py-6">
        <div class=" px-4 md:px-8 mx-auto">
          <div class="swiper-container">
              <div class="swiper mySwiper">
                <div class="swiper-wrapper h-80 w-80">
                  <% unless @graduation_album.images.blobs == [] %>
                    <% @graduation_album.images.each do |image| %> 
                      <%= image_tag image, class:"swiper-slide rounded-lg", id:"album-swiper" %>
                    <% end %>
                  <% else %>
                    <div class='swiper-slide rounded-lg' id="album-swiper"><%= image_tag 'default_album1' %></div>
                    <div class='swiper-slide rounded-lg' id="album-swiper"><%= image_tag 'default_album2' %></div>
                    <div class='swiper-slide rounded-lg' id="album-swiper"><%= image_tag 'default_album3' %></div>
                  <% end %>
                </div><!-- .swiper-wrapper -->
                  <div class="swiper-pagination"></div>
                  <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>
              </div><!-- .swiper mySwiper -->
          </div>
        </div>
      </div>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3"> 
      <div class='text-center py-2'>
        <button class="btn btn-outline btn-primary">
          <%= link_to anchor: "event_top" do %>
            <i class="fa-solid fa-plane fa-lg"></i> イベントへ移動
          <% end %>
        </button>
      </div>
      <div class='text-center py-2'>
        <button class="btn btn-outline btn-secondary">
        <%= link_to anchor: "rank_top" do %>
            <i class="fa-solid fa-ranking-star fa-lg"></i> ランキングへ移動
          <% end %>
        </button>
      </div>
      <div class='text-center py-2'>
        <button class='px-2 py-3 text-green-600 border border-green-500 font-semibold rounded-md hover:bg-green-700 hover:text-white'>
        <%= link_to anchor: "suprise_top" do %>
            <i class="fa-solid fa-gift fa-lg"></i> サプライズメッセージへ移動
          <% end %>
        </button>
      </div>
    </div>
  </div>
</div>
<!-- message for everyone -->
<h2 class="text-blue-600 text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-6 pt-8"><i class="fa-solid fa-people-group"></i> メンバー</h2>
<div class="bg-white py-6 sm:py-8 lg:py-12">
  <div class="max-w-screen-xl px-4 md:px-8 mx-auto">
    <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 lg:gap-8">
      <% @graduation_album.users.each do |user| %>
      <!-- person - start -->
        <div class="flex flex-col items-center bg-blue-100 rounded-lg p-4 lg:p-8">
          <div class="w-24 md:w-32 h-24 md:h-32 bg-gray-200 rounded-full overflow-hidden shadow-lg mb-2 md:mb-4">
            <%= link_to graduation_album_menber_path(@graduation_album, user), class:"w-24 md:w-32 h-24 md:h-32 rounded-full overflow-hidden shadow-lg mb-2 md:mb-4" do %>
              <%= image_tag user.avatar.to_s ,class: "w-full h-full object-cover object-center" %>
            <% end %>
          </div>
          <div>
            <div class="text-indigo-500 md:text-lg font-bold text-center">
              <%= link_to user.name, graduation_album_menber_path(@graduation_album, user)%>
            </div>
          <%= link_to graduation_album_menber_path(@graduation_album, user) do %>
            <p class="text-indigo-500 text-sm md:text-base text-center mb-3 md:mb-4">詳細へ <i class="fa-solid fa-arrow-up-right-from-square fa-lg"></i></p>
          <% end %>
          </div>
        </div>
        <!-- person - end -->
      <% end %>
    </div>
  </div>
</div>
<h2 class="text-red-400 text-2xl lg:text-3xl font-bold text-center pt-4 mb-4 md:mb-6 pt-10"><i class="fa-regular fa-comment"></i> メンバーからのメッセージ</h2>
      <%= render 'message_for_everyones/message_for_everyones', { message_for_everyones: @message_for_everyones } %>
      <%= render 'message_for_everyones/form', { graduation_album: @graduation_album, message_for_everyone: @message_for_everyone } %>
<div class='pt-5'>
  <% if @graduation_album.images %>
    <div class="swiper loopSwiper">
      <div class="swiper-wrapper">
        <% unless @graduation_album.images.blobs == [] %>
    <% @graduation_album.images.each do |image| %>
      <%= image_tag image, class:"swiper-slide rounded-lg", id:"loop-swiper", loading:"lazy" %>
    <% end %>
  <% else %>
    <div class='swiper-slide rounded-lg' id="loop-swiper"><%= image_tag 'default_album1' %></div>
    <div class='swiper-slide rounded-lg' id="loop-swiper"><%= image_tag 'default_album2' %></div>
    <div class='swiper-slide rounded-lg' id="loop-swiper"><%= image_tag 'default_album3' %></div>
    <div class='swiper-slide rounded-lg' id="loop-swiper"><%= image_tag 'default_album1' %></div>
    <div class='swiper-slide rounded-lg' id="loop-swiper"><%= image_tag 'default_album2' %></div>
    <div class='swiper-slide rounded-lg' id="loop-swiper"><%= image_tag 'default_album3' %></div>
  <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="bg-white py-6 sm:py-8 lg:py-12">
  <div class="max-w-screen-xl px-4 md:px-8 mx-auto">
    <div class="mb-5 md:mb-8" id='event_top'>
      <h2 class="text-indigo-700 text-2xl lg:text-3xl font-bold text-center mb-3 mt-8 md:mb-3"><i class="fa-solid fa-plane fa-lg"></i> 思い出の行事</h2>
    </div>
    <% if @events != [] %>
      <%= render 'events/events', { graduation_album: @graduation_album, events: @events } %>
    <% else %>
      <%= render 'event_explanation' %>
    <% end %>
    <div class='flex flex-col text-center py-6'>
      <%= link_to new_graduation_album_event_path(@graduation_album) do %>
        <div class='py-6 px-4'><button class="btn btn-outline btn-primary mx-4">イベントを作成</button>
      <% end %>
      <%= link_to graduation_album_auto_make_events_path(@graduation_album), method: :post do %>
        <button class="btn btn-outline btn-primary">イベントを自動で作成する</button>
      <% end %>
    </div>
    </div>
    
    <div class="mb-10 md:mb-16" id='rank_top'>
      <h2 class="text-pink-500 text-2xl lg:text-3xl font-bold text-center mb-3 mt-6 md:mb-3"><i class="fa-solid fa-ranking-star fa-lg"></i> メンバーランキング</h2>
      <p class="max-w-screen-md text-pink-500 md:text-lg text-center mx-auto">〇〇になりそうな人ランキングを作成しよう</p>
    </div>
    <% if @ranks != [] %>
      <%= render 'ranks/ranks', { graduation_album: @graduation_album, ranks: @ranks} %>
    <% else %>
      <%= render 'rank_explanation' %>
    <% end %>
    <div class='text-center py-6'>
    <%= link_to new_graduation_album_rank_path(@graduation_album) do %>
      <button class="btn btn-outline btn-secondary mx-4">ランキングを作成</button>
    <% end %>
    <%= link_to graduation_album_auto_make_ranks_path(@graduation_album), method: :post do %>
      <button class="btn btn-outline btn-secondary">ランキングを自動で作成する</button>
    <% end %>
    </div>

    <div class="mb-10 md:mb-16" id='suprise_top'>
      <h2 class="text-green-600 text-2xl lg:text-3xl font-bold text-center mb-6 mt-12 md:mb-6"><i class="fa-solid fa-gift fa-lg"></i> サプライズメッセージ</h2>
      <p class="max-w-screen-md text-green-600 md:text-lg text-center mx-auto">未来に向けてメッセージを残そう</p>
    </div>
    <% unless @suprise_messages.empty? %>
      <%= render 'suprise_messages/suprise_messages', { graduation_album: @graduation_album, suprise_messages: @suprise_messages } %>
    <% else %>
      <%= render 'suprise_explanation' %>
    <% end %>
    <div class='text-center py-6'>
    <%= link_to new_graduation_album_suprise_message_path(@graduation_album) do %>
      <div class="m-3">
        <button class="px-2 py-3 text-green-600 border border-green-500 font-semibold rounded-md hover:bg-green-700 hover:text-white">サプライズメッセージを作成</button>
      </div>
    <% end %>
    </div>
  </div>
</div>